### ISSUE TITLE
does not build with dub on Windows 7, 64 bit

### ISSUE THREAD

**Issue by poliklosio** [Pure-D/workspace-d-installer#3]
Console log:

```
C:\D\workspace-d-installer\workspace-d-installer>dub
Performing "debug" build using dmd for x86.
workspace-d-installer ~master: building configuration "application"...
Linking...
Running .\workspace-d-installer.exe
Failed to spawn new process (┼╗─ůdana operacja wymaga podniesienia uprawnie┼ä.)

C:\D\workspace-d-installer\workspace-d-installer>

```

The scrambled text in Polish means something like "permission denied".

Presumably it would work when cmd is open with admin priviledges. This, however, is not undocumented, and I didn't expect that admin priviledges would be needed.

I tried with cmd open as admin and it fails with a different error.

**Comment by Vild** [comment]
What error does it fail with if you run it with the admin privileges?

**Comment by poliklosio** [comment]
> What error does it fail with if you run it with the admin privileges?

That would be issue #5.
I was suggesting here that probably documentation should be improved. I have wasted considerable time trying other things, because I didn't notice that admin priviledges could be an issue. Please, note that a new user does not necessarily know what is the expected behavior, unless an example is shown in the readme file.

**Comment by WebFreak001** [comment]
Can you clone the repository and try again? It works on my windows 10 VM now

**Comment by poliklosio** [comment]
Runs normally now without having to have admin priviledges. Looks fixed to me.

**Comment by WebFreak001** [comment]
ok nice
