### ISSUE TITLE
Error building DCD with the installer

### ISSUE THREAD

**Issue by merlin3000** [Pure-D/workspace-d-installer#6]
I am able tobuild DCD directly using DUB, but when I try to user the installer to build it I get the following error:

**Error: unrecognized file extension d^**

It seems to be related with a command that is too large (too many files as parameters). Due to the size of the log I've attached the log file and the error is in line 475.

The installer continues and it opens VS Code on the msgpack file, I don't know if this is supossed to happen. After that I have to close VS Code and after that it resumes but starts throwing exceptions and ends in error.
[d-installer-dcd-error.txt](https://github.com/Pure-D/workspace-d-installer/files/230315/d-installer-dcd-error.txt)

I'm using Windows 7 x64. DMD version is 2.071.0.
I also tried with 2.068.2 but besides the deprecation warnings the result was the same.

**Comment by WebFreak001** [comment]
it actually works with dub now? ok then I can update the installer. When I wrote the code, the dub command for DCD didn't work
