### ISSUE TITLE
Please, merge workspace-d-installer with workspace-d

### ISSUE THREAD

**Issue by poliklosio** [Pure-D/workspace-d-installer#8]
The shear number of tools that a user needs to install in order to start hacking some D in Visual Studio Code is preposterous:

* dmd
* git
* dub
* dfmt
* dscanner
* dcd
* workspace-d-installer
* workspace-d
* Visual Studio Code
* code-d

Yes, I'm including  workspace-d-installer AND workspace-d AND dcd AND  dscanner AND dfmt at the same time, because every user has to spend time investigating what they are before deciding what to do, regardless of how many he actually clones and runs manually. It took me at least half a day to figure what is what and what installs what, and I *did* have prior knowledge of what git, dmd, dcd, dfmt and dscanner are.

The graph of dependencies between them is non-trivial. Overall, its a beast.
In my opinion, very few people will actually go through with this unless they have some prior knowledge about D ecosystem and very strong motivation.

Please, simplify it. 
The first step which seems obvious is to merge workspace-d and workspace-d-installer. It is weird that they are separated, as the general convention is to have installers inside projects.

The way I envision it:
The workspace-d-installer project should not exist. Part of the workspace-d-installer which installs dcd, dscanner and dfmt should really be an install-dependencies.sh and install-dependencies.bat scripts inside the workspace-d project. They can still run D code in the background, nobody cares about that as long as people can run a script format of their platform. Then there should be a simplified way to install workspace-d itself, for example:

    install.sh

or

    install.bat

which should fail with informative error message when the dependencies are not met.

**Comment by WebFreak001** [comment]
Good idea, gonna do it later today. `code-d` could also help you install the extension with that then on first run
